# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb92bb5d173c79235c46822d469445e72f2a07b35e01c37b8ba8f97d5b2b41715ad572f9315b18845ee503fe3e5c9617751e4a1e914e74ceb11f04b42ce3a9f

test:
  secret_key_base: b7b379a3f02118e6bbd1f1a2e5e42866115acb5d26e7d6d928f860304454b10c980bb607ace0552e5209208306a01dbb4c7e14e916ae658d935a25b74e17e10a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
